language: android

# To use Travis Container-Based Infrastructure
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-21.1.0
    - android-21
    - extra-google-google_play_services
    - sys-img-armeabi-v7a-android-21


before_script:
  - curl -O https://pypi.python.org/packages/source/v/virtualenv/virtualenv-12.0.5.tar.gz
  - tar xvfz virtualenv-12.0.5.tar.gz
  - python virtualenv-12.0.5/virtualenv.py venv
  - ./venv/bin/pip install -r requirements.txt
  - echo no | android create avd --force -n testAvd -t android-21 --abi armeabi-v7a
  - emulator -avd testAvd -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &


script:
  - ./gradlew clean build
  - ./venv/bin/nosetests . -v


deploy:
  provider: releases
  api_key:
    secure: Si6dy+ETFBwsbbjMOd9WI8ho0TMDnL46/vhKxLc5Rlvh75UUZH/ThEht/eRhZBP4IgEyg1oeR/8NOL8Lg70aA/cnv0c1+3u050MrUgDIMbbVwgo/l1v7CXfHvRYmicwcn5l9+qhcVaS3Lp7rftfeEvUgXLwwPS0kRxHZuINIYw8=
  file_glob: true
  file: ${HOME}/build/${TRAVIS_REPO_SLUG}/App/build/outputs/apk/lokki-v*-debug.apk
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: TheSoftwareFactory/lokki-android
